name: Pre-Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.9'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
    
    - name: Run tests
      id: tests
      run: |
        pytest tests/ --cov=src --cov-report=xml
        echo "tests_passed=true" >> $GITHUB_OUTPUT
    
    - name: Run linting
      id: lint
      run: |
        flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/ tests/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        echo "lint_passed=true" >> $GITHUB_OUTPUT
    
    - name: Upload coverage report
      if: steps.tests.outputs.tests_passed == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml 